In [1]:
import numpy as np

In [2]:
num = np.array([56,33,12,78,52,68,25])

In [3]:
num

array([56, 33, 12, 78, 52, 68, 25])

In [4]:
type(num)

numpy.ndarray

In [5]:
print(num)

[56 33 12 78 52 68 25]


In [6]:
num.dtype

dtype('int64')

In [8]:
num = np.array([56,33,12,78,52,68,25], dtype = np.int16)

In [9]:
num

array([56, 33, 12, 78, 52, 68, 25], dtype=int16)

In [11]:
num[5]

68

In [12]:
num[5] = 61
num

array([56, 33, 12, 78, 52, 61, 25], dtype=int16)

In [13]:
num.ndim

1

In [14]:
num.min()

12

In [15]:
num.max()

78

In [16]:
num.std()

21.204543217462255

In [17]:
num1 = np.array([45.67, 23.56, 78.25, 89.03])

In [18]:
num1.dtype

dtype('float64')

In [19]:
num * 2

array([112,  66,  24, 156, 104, 122,  50], dtype=int16)

In [20]:
num

array([56, 33, 12, 78, 52, 61, 25], dtype=int16)

In [21]:
num > 40

array([ True, False, False,  True,  True,  True, False])

In [22]:
num[num > 40]

array([56, 78, 52, 61], dtype=int16)

##### Matrix

In [25]:
M = np.array([[5,6,7],[2,4,3],[6,8,9],[0,1,3]])

In [26]:
M

array([[5, 6, 7],
       [2, 4, 3],
       [6, 8, 9],
       [0, 1, 3]])

In [27]:
M.ndim

2

In [28]:
M.shape

(4, 3)

In [29]:
M.size

12

In [30]:
M[0][1]

6

In [31]:
M[0,1]

6

In [32]:
M.T

array([[5, 2, 6, 0],
       [6, 4, 8, 1],
       [7, 3, 9, 3]])

In [33]:
M.transpose()

array([[5, 2, 6, 0],
       [6, 4, 8, 1],
       [7, 3, 9, 3]])

In [34]:
M.reshape(6,2)

array([[5, 6],
       [7, 2],
       [4, 3],
       [6, 8],
       [9, 0],
       [1, 3]])

In [35]:
M.flatten()

array([5, 6, 7, 2, 4, 3, 6, 8, 9, 0, 1, 3])

In [37]:
M.reshape(12)

array([5, 6, 7, 2, 4, 3, 6, 8, 9, 0, 1, 3])

In [38]:
M.reshape(-1)

array([5, 6, 7, 2, 4, 3, 6, 8, 9, 0, 1, 3])

In [39]:
M.reshape(-1,4)

array([[5, 6, 7, 2],
       [4, 3, 6, 8],
       [9, 0, 1, 3]])